import { useEffect, useMemo, useState } from 'react'
import { Archive, ArrowLeft, BarChart3, Check, ChevronDown, CircleHelp, Clock3, Inbox, LayoutGrid, LifeBuoy, Menu, MessageSquarePlus, Paperclip, Plus, Search, Send, Settings, Sparkles, Tag, X } from 'lucide-react'
import './App.css'

const STORAGE_KEY = 'ecosat-helpdesk-tickets'
const seedTickets = [
  { id: 'INC-1048', title: 'No puedo acceder a mi cuenta', description: 'El enlace de acceso devuelve un error después de introducir mis credenciales.', priority: 'Alta', status: 'Nuevo', createdAt: '2026-09-07T08:30:00' },
  { id: 'INC-1047', title: 'Error al exportar reporte mensual', description: 'La exportación se queda cargando y no se descarga el archivo CSV.', priority: 'Media', status: 'En progreso', createdAt: '2026-09-06T14:15:00' },
  { id: 'INC-1046', title: 'Actualizar datos de facturación', description: 'Necesito actualizar la dirección fiscal asociada a mi organización.', priority: 'Baja', status: 'Completado', createdAt: '2026-09-04T11:05:00' },
]
const faqs = [
  { question: '¿Cómo restablezco mi contraseña?', answer: 'Selecciona “¿Olvidaste tu contraseña?” en la pantalla de acceso. Recibirás un enlace de recuperación en tu correo registrado.' },
  { question: '¿Dónde puedo consultar mis facturas?', answer: 'Ve a Configuración y abre la sección Facturación. Allí encontrarás tus facturas y métodos de pago.' },
  { question: '¿Cuánto tarda en resolverse una incidencia?', answer: 'El tiempo depende de la prioridad. Las incidencias altas se atienden el mismo día laborable; las medias y bajas se revisan en un máximo de 48 horas.' },
  { question: '¿Puedo cambiar la prioridad de un ticket?', answer: 'Sí. Añade un comentario en el ticket explicando el impacto y nuestro equipo ajustará la prioridad si es necesario.' },
]
const priorityOrder = { Alta: 0, Media: 1, Baja: 2 }
const statusMeta = { Nuevo: { className: 'status-new', dot: 'new-dot' }, 'En progreso': { className: 'status-progress', dot: 'progress-dot' }, Completado: { className: 'status-complete', dot: 'complete-dot' } }
const formatDate = (date) => new Intl.DateTimeFormat('es-ES', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(date))

function App() {
  const [tickets, setTickets] = useState(() => { const saved = localStorage.getItem(STORAGE_KEY); return saved ? JSON.parse(saved) : seedTickets })
  const [screen, setScreen] = useState('help')
  const [filter, setFilter] = useState('all')
  const [selectedId, setSelectedId] = useState(null)
  const [faqOpen, setFaqOpen] = useState(0)
  const [search, setSearch] = useState('')
  const [notice, setNotice] = useState('')
  const [form, setForm] = useState({ title: '', description: '', priority: 'Media' })
  useEffect(() => localStorage.setItem(STORAGE_KEY, JSON.stringify(tickets)), [tickets])

  const activeTicket = tickets.find((ticket) => ticket.status === 'En progreso')
  const selectedTicket = tickets.find((ticket) => ticket.id === selectedId)
  const counts = { all: tickets.length, new: tickets.filter((t) => t.status === 'Nuevo').length, progress: tickets.filter((t) => t.status === 'En progreso').length, completed: tickets.filter((t) => t.status === 'Completado').length }
  const visibleTickets = useMemo(() => {
    const matches = (ticket) => `${ticket.id} ${ticket.title} ${ticket.description}`.toLowerCase().includes(search.toLowerCase())
    let result = tickets.filter(matches)
    if (filter === 'new') result = result.filter((ticket) => ticket.status === 'Nuevo').sort((a, b) => priorityOrder[a.priority] - priorityOrder[b.priority] || new Date(a.createdAt) - new Date(b.createdAt))
    if (filter === 'progress') result = result.filter((ticket) => ticket.status === 'En progreso')
    if (filter === 'completed') result = result.filter((ticket) => ticket.status === 'Completado')
    return filter === 'new' ? result : result.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))
  }, [filter, search, tickets])
  const updateTicketStatus = (id, status) => { setTickets((current) => current.map((ticket) => ticket.id === id ? { ...ticket, status } : ticket)); setNotice(status === 'En progreso' ? 'Incidencia iniciada correctamente.' : 'Incidencia marcada como completada.') }
  const startResolution = (ticket) => { if (activeTicket && activeTicket.id !== ticket.id) { setNotice(`Ya hay una incidencia en progreso (${activeTicket.id}). Finalízala antes de iniciar otra.`); return } updateTicketStatus(ticket.id, 'En progreso'); setSelectedId(ticket.id) }
  const createTicket = (event) => { event.preventDefault(); if (!form.title.trim() || !form.description.trim()) return; const nextTicket = { id: `INC-${1050 + tickets.length}`, ...form, title: form.title.trim(), description: form.description.trim(), status: 'Nuevo', createdAt: new Date().toISOString() }; setTickets((current) => [nextTicket, ...current]); setForm({ title: '', description: '', priority: 'Media' }); setNotice('Ticket creado. El equipo lo revisará pronto.') }
  const goToManager = (nextFilter = 'all') => { setFilter(nextFilter); setScreen('manage'); setSelectedId(null) }

  return <div className="app-shell">
    <header className="topbar"><div className="brand-mark"><span>ec</span><span className="brand-dot">·</span><span>sat</span></div><div className="topbar-context"><span className="context-line" /> <span>{screen === 'help' ? 'Centro de ayuda' : 'Operaciones'}</span></div><div className="topbar-actions"><button className="icon-button mobile-menu" aria-label="Abrir menú"><Menu size={19} /></button><button className="icon-button" aria-label="Ayuda"><CircleHelp size={18} /></button><div className="avatar">AM</div></div></header>
    {screen === 'help' ? <HelpCenter faqs={faqs} faqOpen={faqOpen} setFaqOpen={setFaqOpen} form={form} setForm={setForm} createTicket={createTicket} notice={notice} goToManager={goToManager} /> : <ManagerLayout filter={filter} setFilter={setFilter} counts={counts} search={search} setSearch={setSearch} visibleTickets={visibleTickets} selectedTicket={selectedTicket} setSelectedId={setSelectedId} activeTicket={activeTicket} startResolution={startResolution} updateTicketStatus={updateTicketStatus} notice={notice} goToHelp={() => setScreen('help')} />}
  </div>
}

function HelpCenter({ faqs: questions, faqOpen, setFaqOpen, form, setForm, createTicket, notice, goToManager }) {
  const valid = form.title.trim() && form.description.trim()
  return <main className="help-page"><section className="help-hero"><div className="eyebrow"><Sparkles size={14} /> SOPORTE ECOSAT <span>•</span> 24/7</div><h1>Resuelve lo esencial.<br /><em>Sin esperar.</em></h1><p>Encuentra respuestas rápidas o cuéntanos qué necesitas. Estamos aquí para mantener tu operación en movimiento.</p><div className="hero-actions"><button className="primary-button" onClick={() => document.getElementById('new-ticket').scrollIntoView({ behavior: 'smooth' })}><MessageSquarePlus size={17} /> Crear una incidencia</button><button className="text-button" onClick={() => goToManager('all')}>Ver mis incidencias <ArrowLeft size={16} className="arrow-right" /></button></div></section><section className="faq-layout"><div className="section-intro"><span className="section-kicker">01 / RESPUESTAS</span><h2>Preguntas<br /><span>frecuentes</span></h2><p>Lo que más nos preguntan, explicado de forma sencilla.</p></div><div className="faq-list">{questions.map((faq, index) => <div className={`faq-item ${faqOpen === index ? 'is-open' : ''}`} key={faq.question}><button className="faq-question" onClick={() => setFaqOpen(faqOpen === index ? -1 : index)}><span className="faq-number">0{index + 1}</span><span>{faq.question}</span><ChevronDown size={18} /></button>{faqOpen === index && <div className="faq-answer"><p>{faq.answer}</p></div>}</div>)}</div></section><section id="new-ticket" className="ticket-section"><div className="ticket-copy"><span className="section-kicker">02 / CONTACTO</span><h2>¿No encuentras<br /><span>lo que buscas?</span></h2><p>Abre una incidencia y nuestro equipo se pondrá con ello. Cuantos más detalles, mejor podremos ayudarte.</p><div className="response-note"><Clock3 size={17} /><span><strong>Tiempo de respuesta</strong><br />Normalmente respondemos en menos de 4 horas.</span></div></div><form className="ticket-form" onSubmit={createTicket}><div className="form-heading"><div className="form-icon"><Plus size={19} /></div><div><h3>Nueva incidencia</h3><p>Todos los campos marcados son necesarios.</p></div></div><label>Título de la incidencia<input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="Ej. No puedo iniciar sesión" /></label><label>Descripción<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Describe brevemente qué está ocurriendo..." rows="4" /></label><label>Prioridad<select value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })}><option>Baja</option><option>Media</option><option>Alta</option></select></label><div className="form-footer"><span className="attachment-hint"><Paperclip size={15} /> Puedes adjuntar archivos después</span><button className="primary-button" disabled={!valid} type="submit"><Send size={15} /> Enviar incidencia</button></div></form></section>{notice && <div className="toast"><Check size={16} /> {notice}</div>}</main>
}

function ManagerLayout({ filter, setFilter, counts, search, setSearch, visibleTickets, selectedTicket, setSelectedId, activeTicket, startResolution, updateTicketStatus, notice, goToHelp }) {
  const filterItems = [{ id: 'all', label: 'Inicio / Todos', icon: LayoutGrid }, { id: 'new', label: 'Bandeja de entrada', icon: Inbox }, { id: 'progress', label: 'En progreso', icon: Clock3 }, { id: 'completed', label: 'Completados', icon: Archive }]
  return <main className="manager-page"><aside className="sidebar"><button className="compose-button" onClick={goToHelp}><Plus size={18} /> Nueva incidencia</button><nav>{filterItems.map(({ id, label, icon: Icon }) => <button key={id} className={`nav-item ${filter === id ? 'active' : ''}`} onClick={() => { setFilter(id); setSelectedId(null) }}><Icon size={17} /><span>{label}</span><b>{counts[id]}</b></button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><BarChart3 size={17} /><span>Analítica</span></button><button className="nav-item"><Settings size={17} /><span>Configuración</span></button><div className="sidebar-tip"><LifeBuoy size={17} /><span><strong>Centro de ayuda</strong><br />¿Necesitas orientación?</span><button onClick={goToHelp}>Abrir <ArrowLeft size={13} className="arrow-right" /></button></div></div></aside><section className="inbox-panel"><div className="manager-heading"><div><span className="section-kicker">ESPACIO DE TRABAJO</span><h1>{filter === 'all' ? 'Todas las incidencias' : filter === 'new' ? 'Bandeja de entrada' : filter === 'progress' ? 'En progreso' : 'Completados'}</h1><p>{filter === 'new' ? 'Ordenadas por prioridad y antigüedad.' : 'Gestiona y consulta el estado de tus solicitudes.'}</p></div><div className="manager-count">{visibleTickets.length}<span>tickets</span></div></div><div className="search-field"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por título o número..." />{search && <button onClick={() => setSearch('')} aria-label="Limpiar búsqueda"><X size={15} /></button>}</div>{notice && <div className="manager-notice"><CircleHelp size={15} /> {notice}</div>}{filter === 'progress' && activeTicket ? <ProgressCard ticket={activeTicket} updateTicketStatus={updateTicketStatus} /> : <div className="ticket-list">{visibleTickets.length ? visibleTickets.map((ticket) => <TicketRow key={ticket.id} ticket={ticket} selected={selectedTicket?.id === ticket.id} onClick={() => setSelectedId(ticket.id)} />) : <EmptyState filter={filter} />}</div>}</section>{selectedTicket && filter !== 'progress' && <TicketDetail ticket={selectedTicket} activeTicket={activeTicket} close={() => setSelectedId(null)} startResolution={startResolution} />}</main>
}
function TicketRow({ ticket, selected, onClick }) { const meta = statusMeta[ticket.status]; return <button className={`ticket-row ${selected ? 'selected' : ''}`} onClick={onClick}><span className={`ticket-avatar ${meta.dot}`}>{ticket.title.slice(0, 1)}</span><span className="ticket-row-main"><span className="ticket-row-top"><strong>{ticket.title}</strong><small>{formatDate(ticket.createdAt)}</small></span><span className="ticket-row-bottom"><span>{ticket.id}</span><span className={`status-label ${meta.className}`}><i />{ticket.status}</span><span className="priority-label">{ticket.priority}</span></span></span></button> }
function TicketDetail({ ticket, activeTicket, close, startResolution }) { const meta = statusMeta[ticket.status]; return <aside className="detail-panel"><div className="detail-header"><span>DETALLE DE INCIDENCIA</span><button className="icon-button" onClick={close} aria-label="Cerrar detalle"><X size={18} /></button></div><div className="detail-content"><span className={`status-label ${meta.className}`}><i />{ticket.status}</span><h2>{ticket.title}</h2><div className="detail-id">{ticket.id} <span>•</span> Creado el {formatDate(ticket.createdAt)}</div><div className="detail-divider" /><div className="detail-field"><span>PRIORIDAD</span><strong className={`priority-text priority-${ticket.priority.toLowerCase()}`}>{ticket.priority}</strong></div><div className="detail-field"><span>DESCRIPCIÓN</span><p>{ticket.description}</p></div>{ticket.status === 'Nuevo' && <button className="primary-button full-button" onClick={() => startResolution(ticket)} disabled={Boolean(activeTicket)}><Clock3 size={16} /> {activeTicket ? `En progreso: ${activeTicket.id}` : 'Iniciar resolución'}</button>}{ticket.status === 'Completado' && <div className="read-only"><Check size={16} /> Incidencia resuelta · solo lectura</div>}</div></aside> }
function ProgressCard({ ticket, updateTicketStatus }) { return <div className="active-resolution"><div className="active-label"><span className="pulse-dot" /> INCIDENCIA ACTIVA</div><span className="status-label status-progress"><i />En progreso</span><h2>{ticket.title}</h2><p>{ticket.description}</p><div className="active-meta"><span><Tag size={15} /> {ticket.id}</span><span><Clock3 size={15} /> Desde {formatDate(ticket.createdAt)}</span><span>Prioridad <strong>{ticket.priority}</strong></span></div><button className="complete-button" onClick={() => updateTicketStatus(ticket.id, 'Completado')}><Check size={17} /> Finalizar y completar</button></div> }
function EmptyState({ filter }) { return <div className="empty-state"><Inbox size={31} /><h3>{filter === 'completed' ? 'Aún no hay incidencias completadas' : 'No encontramos incidencias'}</h3><p>Prueba con otro filtro o término de búsqueda.</p></div> }

export default App
